# Generated by Django 5.2.7 on 2025-10-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trelix', '0003_exam_certificate_question_studentexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='student',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='StudentExam',
        ),
    ]
