# Generated by Django 5.2.7 on 2025-10-28 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trelix', '0004_remove_studentexam_exam_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
