# Generated by Django 5.2.7 on 2025-10-28 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('organisateur', 'Organisateur'), ('mentor', 'Mentor'), ('jury', 'Jury')], default='participant', max_length=20)),
                ('niveau_etude', models.CharField(choices=[('lyceen', 'Lycéen'), ('etudiant', 'Étudiant'), ('ingenieur', 'Ingénieur'), ('professionnel', 'Professionnel')], max_length=20)),
                ('domaine_competence', models.CharField(choices=[('developpement_web', 'Développement web'), ('data_science', 'Data Science'), ('design', 'Design'), ('cybersecurite', 'Cybersécurité'), ('ia', 'IA')], max_length=30)),
                ('experience_precedente', models.BooleanField(default=False)),
                ('annee_experience', models.PositiveIntegerField(default=0)),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'unique_together': {('utilisateur', 'evenement')},
            },
        ),
    ]
