# Generated by Django 5.2.7 on 2025-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_remove_course_duration_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Au moins 10 caractères. Ne commencez pas par un chiffre ou un symbole.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Au moins 5 caractères. Ne commencez pas par un chiffre ou un symbole.', max_length=255),
        ),
    ]
