# Generated by Django 5.2.7 on 2025-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_course_description_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text="At least 10 characters. Don't start with a symbol or a number."),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text="At least 5 characters. Don't start with a symbol or a number.", max_length=255),
        ),
    ]
