# Generated by Django 5.2.7 on 2025-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('webinaire', 'Webinaire'), ('conference', 'Conférence'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('capacite_max', models.PositiveIntegerField()),
            ],
        ),
    ]
