# Generated by Django 5.2.7 on 2025-10-29 12:09

import evenement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_alter_evenement_date_debut_alter_evenement_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(help_text='Au moins 5 caractères. Ne doit pas commencer par un symbole ou un chiffre. Lettres uniquement.', max_length=40, validators=[evenement.models.validate_letters_only, evenement.models.validate_start_with_letter]),
        ),
    ]
