# Generated by Django 5.2.7 on 2025-10-29 22:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_alter_evenement_image_alter_evenement_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
