# Generated by Django 5.2.7 on 2025-10-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_badge_on_success_badge_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='badge_on_success',
            field=models.ForeignKey(blank=True, help_text='Badge attribué si le score minimum est atteint', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.badge'),
        ),
    ]
