# Generated by Django 5.2.7 on 2025-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_userbadge_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
