"""
Django settings for Trelix project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sys

# -------------------------------------------------------------
# 📁 BASE & ENV
# -------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis le fichier .env
load_dotenv(BASE_DIR / '.env')

print("DB_NAME:", os.getenv("DB_NAME"))
print("DB_USER:", os.getenv("DB_USER"))
print("Filesystem encoding:", sys.getfilesystemencoding())

# -------------------------------------------------------------
# 🔐 SECURITY
# -------------------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key')
DEBUG = True
ALLOWED_HOSTS = []

# -------------------------------------------------------------
# ⚙️ APPLICATIONS
# -------------------------------------------------------------
INSTALLED_APPS = [
    'jazzmin',  # Thème admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps locales
    'Trelix',
    'cours',
    'chapitre',
    'evenement',
    'examan',
    'participation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Trelix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # ✅ pour MEDIA_URL
            ],
        },
    },
]

WSGI_APPLICATION = 'Trelix.wsgi.application'

# -------------------------------------------------------------
# 🗄️ DATABASE
# -------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# -------------------------------------------------------------
# 🔑 API KEYS (ex: Hugging Face / Google)
# -------------------------------------------------------------
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
IMAGEGEN_KEY = os.getenv('IMAGEGEN_KEY')  # ✅ pour la génération d'images

# -------------------------------------------------------------
# 🔐 PASSWORD VALIDATION
# -------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------------
# 🌍 INTERNATIONALIZATION
# -------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------
# 🖼️ STATIC & MEDIA FILES
# -------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'Trelix' / 'static']  # ou "static" selon ton projet
STATIC_ROOT = BASE_DIR / 'staticfiles'  # utile pour collectstatic en prod

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------
# 🧱 DEFAULT PRIMARY KEY FIELD
# -------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
