"""
Django settings for Trelix project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import sys

# -------------------------------------------------------------
# 📁 BASE & ENV
# -------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Charger les variables d'environnement depuis le fichier .env
load_dotenv(BASE_DIR / '.env')

print("DB_NAME:", os.getenv("DB_NAME"))
print("DB_USER:", os.getenv("DB_USER"))
print("Filesystem encoding:", sys.getfilesystemencoding())

# -------------------------------------------------------------
# 🔐 SECURITY
# -------------------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key')
DEBUG = True
ALLOWED_HOSTS = []

# -------------------------------------------------------------
# ⚙️ APPLICATIONS
# -------------------------------------------------------------
INSTALLED_APPS = [
    'jazzmin',  # Thème admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps locales
    'Trelix',
    'cours',
    'chapitre',
    'evenement',
    'examan',
    'participation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Trelix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # ✅ pour MEDIA_URL
            ],
        },
    },
]

WSGI_APPLICATION = 'Trelix.wsgi.application'

# -------------------------------------------------------------
# 🗄️ DATABASE
# -------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# -------------------------------------------------------------
# 🔑 API KEYS (ex: Hugging Face / Google)
# -------------------------------------------------------------
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
IMAGEGEN_KEY = os.getenv('IMAGEGEN_KEY')  # ✅ pour la génération d'images

# -------------------------------------------------------------
# 🔐 PASSWORD VALIDATION
# -------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------------
# 🌍 INTERNATIONALIZATION
# -------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------
# 🖼️ STATIC & MEDIA FILES
# -------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"), 
]



# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========================
# 🎨 JAZZMIN CONFIGURATION
# ========================
JAZZMIN_SETTINGS = {
    "site_title": "Trelix Admin",
    "site_header": "Trelix Dashboard",
    "site_brand": "Trelix",
    "welcome_sign": "Welcome to the Trelix Admin Dashboard 👋",
    "copyright": "© 2025 Trelix | All rights reserved",
    
    # 🌗 Theme
    "show_ui_builder": True,
    "theme": "materia",  # You can also try: flatly, darkly, minty, solar, etc.
    
    # 🧭 Top Menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Website", "url": "/", "new_window": True},
    ],

    # 🧩 Sidebar
    "order_with_respect_to": ["auth", "Trelix"],

    # 💎 Custom icons for each model
    "icons": {
        "auth": "fas fa-user-shield",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "Trelix.Exam": "fas fa-file-alt",
        "Trelix.Question": "fas fa-question-circle",
        "Trelix.StudentExam": "fas fa-graduation-cap",
        "Trelix.Certificate": "fas fa-award",
    },

    # 🌍 Customization
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
}

# Optional: extra colors and layout tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "footer_fixed": True,
    "theme": "darkly",
    "body_small_text": True,
    "sidebar_fixed": True,
    "sidebar_light": False,
    "button_classes": {
        "primary": "btn-primary",
        "success": "btn-success",
    },
}
JAZZMIN_SETTINGS["site_logo"] = "images/trelix_blanc.png"

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------
# 🧱 DEFAULT PRIMARY KEY FIELD
# -------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
