# Generated by Django 5.2.7 on 2025-10-28 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video (mp4, mov, avi)', null=True, upload_to='chapters/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(help_text="At least 10 characters. Can't start with a symbol or a number."),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text="At least  5 characters. Can't start with a symbol or a number.", max_length=200),
        ),
    ]
